name: breast_cancer
channels:
  - conda-forge
  - pip:
    - matplotlib==3.5.1
    - pandas==1.4.2
    - pillow==6.2.2
    - scikit-learn==1.1.2
    - scipy==1.8.0
    - seaborn==0.11.2
    - tqdm==4.64.0