name: temp10
channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - pip:
    - matplotlib==3.5.1
    - pandas==1.4.2
    - pillow
    - scikit-learn==1.1.2
    - scipy
    - seaborn==0.11.2
    - tqdm==4.64.0